MAIN_DOMAIN: realnia.com
SECRET_KEY_BASE: 1234..1234
DEVISE_SECRET_KEY: 1234..1234
SMTP_DOMAIN: mail.realnia.com
MAILGUN_API_KEY=key-d9b386e0a10afe0f77b55c5de0d56e44
# MAILCHIMP_API_KEY: f....3333-ek3
# MAILCHIMP_LIST_ID: 9982...112
ADMIN_EMAILS: chris@keybridge.net
# RECAPTCHA_SITE_KEY: 6Lc6BAAAAAAAAChqRbQZcn_yyyyyyyyyyyyyyyyy
# RECAPTCHA_SECRET_KEY: 6Lc6BAAAAAAAAKN3DRm6VA_xxxxxxxxxxxxxxxxx
# CLARIFAI_V2_API_KEY: asdl2k34jl2kn1l2hn234
# CLARIFAI_V2_NSFW_MODEL: asdflkj23498oihlj2n34kn23
# INTERCOM_APP_ID: 1234k2k3
# INTERCOM_API_SECRET: asdfljknwasdfnwebiaskjfbiuh
GOOGLE_ANALYTICS_ID=UA-12345-67 ## ONLY FOR PRODUCTION
